### ISSUE TITLE
Opening Links in new tab

### ISSUE THREAD

**Issue by MeowMeowVenom** [ramesh-dada/download-button#1]
Rather than making opening links in new tab as the default, can you provide a toggle to disable it?
I kinda need this option for preventing hotlinking of content

**Comment by MeowMeowVenom** [comment]
```
target="_blank" 
```

Removing this helped, but it will be nice to have a toggle

**Comment by ramesh-dada** [comment]
You haven't updated the extension this feature is already there, Go ahead and update to latest version by using 

```composer require ramesh-dada/download-button:*```

**Comment by MeowMeowVenom** [comment]
![image](https://user-images.githubusercontent.com/62835853/134294690-df256974-d208-4307-bca9-2e40ffea14e1.png)
Nope there is no toggle (I am on the latest version)

If you did not understand me, I want a toggle that decides if links open in new tab, or not

**Comment by ramesh-dada** [comment]
@Rejected-Peice By default all the links are opening in new tab.
